---
apiVersion: v1
kind: Service
metadata:
  name: {{ build.name }}
  namespace: {{ service.namespace | default("default") }}
spec:
  type: ClusterIP
  ports:
    - name: http-api
      port: 80
      targetPort: http-api
  selector:
    app: {{ build.name }}
